## Colorectal cancer prognostic risk score tool ##

library(shinyjs)
library(shiny)
library(plotly)
library(survival)

## load dataset
load("train_with_clinical.RData") ### clinical + genetic training set

## load trained model
cox_combined = readRDS("cox_combined.RDS")

cox_model <- coxph(Surv(survival_time, censored_status) ~ risk_combined, data = train_with_clinical)

## define UI

ui <- fluidPage(
  useShinyjs(),  # Initialize shinyjs for JavaScript operations
  tags$head(tags$style(HTML("
        #mainContent, #infoPage, #aboutPage{\
        display: none; /* Hide other pages initially */\
        }\
        #landingPage {
        text-align: center;
        padding-top: 10%;
        background-image: url('wallpaper.png');
        background-size: cover
        background-position: center;
        opacity: 0.80; /* Adjust background opacity */
        height: 100vh;  # Makes the div full viewport height
        }
        #scrollableSidebar {
        max-height: 90vh; /* Limit height to 90% of the viewport */
        overflow-y: auto; /* Enable vertical scrolling */
        padding-right: 10px; /* Add space for scrollbar */
        }
        #getStartedBtn {
        background-color: #D8BFD8 !important; /* Light purple */
        border-color: #D8BFD8 !important;
        color: black !important;
        font-weight: bold;
        }
        #helpBtn {
        background-color: #D8BFD8 !important; /* Light purple */
        border-color: #D8BFD8 !important;
        color: black !important;
        font-weight: bold;
        }
        #footerText {\
        position: absolute;\
        bottom: 10px;\
        right: 20px;\
        font-size: 12px;\
        color: black;\
        opacity: 0.7;\
        }\
        #aboutBtn {\
        position: absolute;\
        bottom: 10px;\
        left: 20px;\
        background-color: #D8BFD8 !important; /* Light purple */\
        border-color: #D8BFD8 !important;\
        color: black !important;\
        font-weight: bold;\
        }\
        #backToHomeBtn {\
        background-color: #D8BFD8 !important; /* Light purple */\
        border-color: #D8BFD8 !important;\
        color: black !important;\
        font-weight: bold;\
        margin-top: 20px;\
        }\
        #findOutMoreBtn {\
        background-color: #D8BFD8 !important; /* Light purple */\
        border-color: #D8BFD8 !important;\
        color: black !important;\
        font-weight: bold;\
        margin-top: 20px;\
        display: block; /* Stack buttons vertically */\
        margin: 10px auto; /* Center align */\
        }\
    "))),
  
  # Landing page content
  div(id = "landingPage",
      h1("Colorectal Cancer Genie (ColoGenie)"),
      h2("DNA methylation biomarkers for colorectal cancer survival prediction"),
      br(),
      actionButton("findOutMoreBtn", "Find out more!", class = "btn btn-success btn-lg"),
      actionButton("getStartedBtn", "Try it out!", class = "btn btn-success btn-lg"),
      actionButton("aboutBtn", "About Us", class = "btn btn-success btn-lg"),
      div(id = "footerText", "Background image generated by AI")
  ),
  
  # Info page, which is initially hidden
  div(id = "infoPage",
      actionButton("backToHomeBtn", "Back to Home", class = "btn btn-lg"),
      h1("What is ColoGenie?"),
      h3("ColoGenie, an AI-based prognostic risk scoring tool, predicts colorectal cancer survival based on methylation and clinical factors."),
      h4("Colorectal cancer affects millions worldwide and bears a substantial disease burden, yet cancer patients often have vastly different survival outcomes. To facilitate tailored treatments, survival prediction of colorectal cancer is crucial. Our study identified a novel set of biomarkers to predict cancer survival by analysing DNA methylation patterns in TCGA datasets. Using machine learning, 10 DNA methylation markers that are predictive of colorectal cancer overall survival were identified."),
      img(src = "flowchart.png", width = "80%"),
      br()
  ),
  
  # About Us page, which is intially hidden
  div(id = "aboutPage",
      actionButton("backToHomeBtn", "Back to Home", class = "btn btn-lg"),
      h2("About Us"),
      h4("This work is led by A/Prof Caroline Lee from the Department of Biochemistry, Yong Loo Lin School of Medicine, National University of Singapore. The full author list is as shown below:"),
      h4("Qiaojing Chen^ [1], Jia Wei Lee^ [1],[2], Kenneth H.K. Ban [1], Caroline G. Lee [1],[2],[3]"),
      h4("1. Department of Biochemistry, Yong Loo Lin School of Medicine, National University of Singapore, Singapore 117596, Singapore"),
      h4("2. NUS Graduate School, National University of Singapore, Singapore 119077, Singapore"),
      h4("3. Duke-NUS Medical School, Singapore 169857, Singapore"),
      h4("^Qiaojing Chen and Jia Wei Lee should be considered joint first authors."),
      h4("Corresponding Author: Caroline G. Lee, Ph.D. Department of Biochemistry, Yong Loo Lin School of Medicine, National University of Singapore, C/O MD7, Level 2, 8 Medical Drive, Singapore, 117597, Singapore"),
      h4("Tel: (+65) 65163251. E-mail: bchleec@nus.edu.sg"),
      br()
  ),
  
  # Main content, which is initially hidden
  div(id = "mainContent",
      actionButton("backToHomeBtn", "Back to Home", class = "btn btn-lg"),
      h1("ColoGenie Prognostic Risk Score Calculator"),
      h3(div(HTML("Indicate the patient's clinical and methylation data"))),
      actionButton("helpBtn", "Help", icon = icon("info-circle"), class = "btn btn-lg"),
      #create client side input form
      sidebarLayout(
        sidebarPanel(
          div(
            id = "scrollableSidebar",
            # clinical variables
            sliderInput(inputId = 'age', label = 'Age', min=20, max=100, value=40, step=1, round=0),
            selectInput(inputId = 'gender', label = 'Gender', choices = c("male", "female")),
            selectInput(inputId = 'stage', label = 'AJCC Pathologic Stage', choices = c("Stage I", "Stage II", "Stage III", "Stage IV")),
            # methylation variables
            sliderInput(inputId = 'cg02922563', label = 'cg02922563', min=0, max=1,value=0, step=0.001, round=0.001),
            sliderInput(inputId = 'cg01259619', label = 'cg01259619', min=0, max=1,value=0, step=0.001, round=0.001),
            sliderInput(inputId = 'cg03976567', label = 'cg03976567', min=0, max=1,value=0, step=0.001, round=0.001),
            sliderInput(inputId = 'cg09414535', label = 'cg09414535', min=0, max=1,value=0, step=0.001, round=0.001),
            sliderInput(inputId = 'cg13410437', label = 'cg13410437', min=0, max=1,value=0, step=0.001, round=0.001),
            sliderInput(inputId = 'cg19841506', label = 'cg19841506', min=0, max=1,value=0, step=0.001, round=0.001),
            sliderInput(inputId = 'cg14008119', label = 'cg14008119', min=0, max=1,value=0, step=0.001, round=0.001),
            sliderInput(inputId = 'cg12119029', label = 'cg12119029', min=0, max=1,value=0, step=0.001, round=0.001),
            sliderInput(inputId = 'cg04586023', label = 'cg04586023', min=0, max=1,value=0, step=0.001, round=0.001),
            sliderInput(inputId = 'cg03406535', label = 'cg03406535', min=0, max=1,value=0, step=0.001, round=0.001)
          )),
        mainPanel(
          # Output: Interactive histogram plot
          div(plotlyOutput(outputId = "histogram")),
          hr(),
          # Display PRS value
          div(textOutput("text"),style = "font-size: 24px;color: purple;"), 
          # Display probability
          div(textOutput("text2"),style = "font-size: 24px;color: purple;"),
          tags$p("This tool is currently for research purposes only", style = "font-size: 16px; color: black;")
        ))
  ))

## define server logic

server <- function(input, output, session) {
  
  # Logic for the landing page to transition to the main content
  observeEvent(input$getStartedBtn, {
    # Hide the landing page and show the main content
    shinyjs::hide("landingPage")
    shinyjs::hide("infoPage")
    shinyjs::hide("aboutPage")
    shinyjs::show("mainContent")
  })
  
  # Logic for the landing page to transition to the info page
  observeEvent(input$findOutMoreBtn, {
    # Hide the landing page and show the info page
    shinyjs::hide("landingPage")
    shinyjs::hide("mainContent")
    shinyjs::hide("aboutPage")
    shinyjs::show("infoPage")
  })
  
  # Logic to transition to the landing page
  observeEvent(input$backToHomeBtn, {
    shinyjs::hide("mainContent")
    shinyjs::hide("infoPage")
    shinyjs::hide("aboutPage")
    shinyjs::show("landingPage")
  })
  
  # Logic to transition to the the aboout page
  observeEvent(input$aboutBtn, {
    shinyjs::hide("mainContent")
    shinyjs::hide("infoPage")
    shinyjs::hide("landingPage")
    shinyjs::show("aboutPage")
  })
  
  ## help button
  observeEvent(input$helpBtn, {
    showModal(modalDialog(
      title = "How to Use the ColoGenie Calculator",
      "This tool calculates the patient's prognostic risk score for colorectal cancer survival. 
    Follow these steps:
    
    1. Input the patient's clinical variables.
    2. Input beta values for the 10 identified methylation sites.
    3. View the patient's risk score and 3-year survival probability.
    
    Note: This tool is currently for research purposes only.",
      easyClose = TRUE,
      footer = modalButton("Close")
    ))
  })
  
  ## calculate PRS
  prs_calculate <- reactive({
    
    new_data <- data.frame(
      age = as.numeric(input$age),
      gender = factor(
        input$gender,
        levels = levels(train_with_clinical$gender)
      ),
      stage_simplified = factor(
        input$stage,
        levels = levels(train_with_clinical$stage_simplified)
      ),
      cg02922563 = as.numeric(input$cg02922563),
      cg01259619 = as.numeric(input$cg01259619),
      cg03976567 = as.numeric(input$cg03976567),
      cg09414535 = as.numeric(input$cg09414535),
      cg13410437 = as.numeric(input$cg13410437),
      cg19841506 = as.numeric(input$cg19841506),
      cg14008119 = as.numeric(input$cg14008119),
      cg12119029 = as.numeric(input$cg12119029),
      cg04586023 = as.numeric(input$cg04586023),
      cg03406535 = as.numeric(input$cg03406535)
    )
    
    predicted_PRS <- predict(cox_combined, newdata = new_data, type = "lp")
    return(predicted_PRS)
  })
  
  # Render PRS
  output$text <- renderText({
    paste("The patient's risk score is:", round(prs_calculate(),digits=2))
  })
  
  # Function to calculate survival probability based on PRS
  
  prob_calculate <- reactive({
    prs <- prs_calculate()
    # Fit Cox proportional hazards model
    sf <- survfit(cox_model, newdata = data.frame(risk_combined = prs))
    summary(sf, times = 3*365)$surv * 100
  })
  
  ## Render surv probability
  
  output$text2 <- renderText({
    prob <- prob_calculate()
    
    if (is.na(prob)) {
      return("Probability of 3-year survival: unavailable")
    }
    
    paste0("Probability of 3-year survival: ", round(prob, 2), "%")
  })
  
  # Render histogram plot
  output$histogram <- renderPlotly({
    
    # Create plotly histogram with a vertical line at the summed value
    p <- plot_ly(x = train_with_clinical$risk_combined, type = "histogram",name="Histogram of risk scores") %>%
      layout(title = paste("Distribution of Prognostic Risk Scores"),
             xaxis = list(title = "Prognostic Risk Score"))
    
    # Add vertical line to indicate risk score
    p <- add_trace(p, x = c(prs_calculate(),prs_calculate()), y=c(0,150),type = "scatter", mode = "lines", name = "Patient's Risk Score", line = list(color = "red"))
    
    p
  })
  
}

## run the application
shinyApp(ui = ui, server = server)

## press run app at the end of the entire script